# Generated by Django 3.2.9 on 2022-09-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='user_permissions',
        ),
    ]
