# Generated by Django 3.2.9 on 2022-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220914_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='username',
            field=models.CharField(default=1, max_length=10000, unique=True, verbose_name='Юзер'),
            preserve_default=False,
        ),
    ]
