# Generated by Django 3.2.9 on 2022-09-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_shopuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='username',
        ),
    ]
