# Generated by Django 3.2.9 on 2022-09-14 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import src.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_shopuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PountIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', src.utils.fields.CityField(blank=True, choices=[], max_length=25, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес пункта выдачи')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP code')),
            ],
            options={
                'verbose_name': 'Адрес выдачи',
                'verbose_name_plural': 'Адреса выдачи',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Unrecognized'), (1, 'Recognized'), (2, 'Is staff')], max_length=20, verbose_name='Статус покупателя')),
                ('point_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customer.pountissue', verbose_name='Пункт доставки покупателя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
