# Generated by Django 3.2.9 on 2022-09-18 07:54

from django.db import migrations
import src.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_pountissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pountissue',
            name='city',
            field=src.utils.fields.CityField(blank=True, max_length=25, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=src.utils.fields.CityField(blank=True, max_length=25, null=True, verbose_name='Город'),
        ),
    ]
