# Generated by Django 3.2.9 on 2022-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220918_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_query',
            field=models.TextField(default=1, max_length=5000, verbose_name='Запросы продуктов'),
            preserve_default=False,
        ),
    ]
