# Generated by Django 3.2.9 on 2022-10-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20221013_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('0', 'Unrecognized'), ('1', 'Recognized'), ('2', 'Is staff')], max_length=20, verbose_name='Статус покупателя'),
        ),
    ]
