# Generated by Django 3.2.9 on 2022-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categoryfeature_productfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение категории'),
            preserve_default=False,
        ),
    ]
