# Generated by Django 3.2.9 on 2022-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220927_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tezone_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
