# Generated by Django 3.2.9 on 2022-12-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Описание акции'),
        ),
    ]
