# Generated by Django 3.2.9 on 2023-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230228_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='query_product',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер плитки'),
        ),
    ]
