# Generated by Django 3.2.9 on 2022-09-18 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(0, 'No verify'), (1, 'Verify')], max_length=30, null=True, verbose_name='Верификация')),
                ('title', models.CharField(max_length=50, verbose_name='Название компании')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон компании')),
                ('rating_product', models.FloatField(default=0.0, verbose_name='Рейтинг продуктов')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип компании')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('premium_seller', models.BooleanField(default=False, verbose_name='Премиум продавец')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
